<?php
// $Id: user_service.module,v 1.3.2.16.2.7 2010/05/22 22:56:23 heyrocker Exp $

/**
 * @file
 *  Link general user functionalities to services module.
 */

/**
 * Implementation of hook_perm().
 */
function anonymous_tvchat_service_perm() {
  return array(
    'anonymous_tvchat_service from remote',
  );
}

/**
 * Implementation of hook_service().
 */
function anonymous_tvchat_service_service() {
  return array(

    // user.signup
    array(
      '#method'           => 'user.signup',
      '#callback'         => 'anonymous_tvchat_service_signup',
      '#access arguments' => array('anonymous_tvchat_service from remote'),
      '#file'             => array('file' => 'inc', 'module' => 'anonymous_tvchat_service'),
      '#args'             => array(
        array(
          '#name'           => 'nick',
          '#type'           => 'string',
          '#optional'       => false,
          '#description'    => t('user nickname. profile nickname.'),
        ), 
        array(
          '#name'           => 'email',
          '#type'           => 'string',
          '#optional'       => false,
          '#description'    => t('email address. profile nickname.'),
        ), 
        array(
          '#name'           => 'phone_number',
          '#type'           => 'string',
          '#optional'       => false,
          '#description'    => t('user phone number'),
        ),
        array(
          '#name'           => 'fname',
          '#type'           => 'string',
          '#optional'       => true,
          '#description'    => t('file name including extension.'),
        ), 
        array(
          '#name'           => 'picture',
          '#type'           => 'string',
          '#optional'       => true,
          '#description'    => t('file data base64 encoded.'),
        ), 
        array(
          '#name'           => 'token_APNS',
          '#type'           => 'string',
          '#optional'       => true,
          '#description'    => t('device token for APNS'),
        ), 
        array(
          '#name'           => 'status',
          '#type'           => 'int',
          '#optional'       => true,
          '#default'        => 1,
          '#description'    => t('status 1 - active , 0 - blocked.'),
        ), 
        array(
          '#name'           => 'token_C2DM',
          '#type'           => 'string',
          '#optional'       => true,
          '#description'    => t('device token for C2DM'),
        ), 
      ),
      '#return'           => 'struct',
      '#help'             => t('Save user details.')
    ),

    array(
        '#method'           => 'user.login',
        '#callback'         => 'anonymous_tvchat_service_login',
        '#access arguments' => array('anonymous_tvchat_service from remote'),
        '#file'             => array('file' => 'inc', 'module' => 'anonymous_tvchat_service'),
        '#args'             => array(
            array(
                '#name'           => 'username',
                '#type'           => 'string',
                '#description'    => t('A valid username.'),
                ),
            array(
                '#name'           => 'password',
                '#type'           => 'string',
                '#description'    => t('A valid password.'),
                ),
            array(
                '#name'           => 'phone_number',
                '#type'           => 'string',
                '#optional'       => true,
                '#description'    => t('A valid phone number.'),
                ),

        ),
      '#return'           => 'struct',
      '#help'             => t('Logs in a user.')
    ),

    array(
        '#method'   => 'tvchat.audience_list',
        '#file'     => array('file' => 'inc', 'module' => 'anonymous_tvchat_service'),
        '#callback' => 'anonymous_tvchat_service_audience_list',
        '#access arguments'  => array('anonymous_tvchat_service from remote'),
        '#args'             => array(
            array(
                '#name'           => 'showId',
                '#type'           => 'int',
                '#optional'       => false,
                '#description'    => t('showId (nid).'),
            ),
            array(
                '#name'           => 'flag_friend',
                '#type'           => 'int',
                '#optional'       => false,
                '#description'    => t(' 0 - annonymous 1- friend '),
            ),
            array(
                '#name'           => 'offset',
                '#type'           => 'int',
                '#optional'       => true,
                '#description'    => t('default = 0, starts with 0'),
            ),
            array(
                '#name'           => 'limit',
                '#type'           => 'int',
                '#optional'       => true,
                '#description'    => t('default - 20, count of record'),
            ),
        ),
        '#return'   => 'struct',
        '#help'     => t('List of contact list.')
    ),
    
    array(
        '#method'   => 'tvchat.anonymous_list',
        '#file'     => array('file' => 'inc', 'module' => 'anonymous_tvchat_service'),
        '#callback' => 'anonymous_tvchat_service_anonymous_list',
        '#access arguments'  => array('anonymous_tvchat_service from remote'),
        '#args'             => array(
            array(
                '#name'           => 'offset',
                '#type'           => 'int',
                '#optional'       => true,
                '#description'    => t('default = 0, starts with 0'),
            ),
            array(
                '#name'           => 'limit',
                '#type'           => 'int',
                '#optional'       => true,
                '#description'    => t('default - 40, count of record'),
            ),
        ),
        '#return'   => 'struct',
        '#help'     => t('List of contact list.')
    ),
  );
}

